name: AdvancedAchievements
main: com.hm.achievement.AdvancedAchievements
version: 2.2.1
author: DarkPyves
softdepend: [Vault]
load: POSTWORLD
description: Advanced Achievements enables unique and challenging achievements. Try to collect as many as you can, earn rewards, climb the rankings and receive RP books!
website: https://github.com/PyvesB/AdvancedAchievements
commands:
  aach:
    description: Main Advanced Achievements command, use it to list sub-commands. 
    aliases: [advancedachievements,aachievements,aa]  
    usage: /<command>
permissions:
  achievement.get:
    description: Allows to receive achievements.
    default: true
  achievement.book:
    description: Allows to receive achievements books.
    default: true
  achievement.list:
    description: Allows to display  name of received and missing achievements.
    default: true
  achievement.reload:
    description: Allows to reload the plugin's configuration.
    default: op
  achievement.give:
    description: Allows to give achievements by command.
    default: op
  achievement.check:
    description: Allows to check if achievements were received by players.
    default: op
  achievement.*:
    description: Star notation of permissions, includes all of them.
    default: op
    children:
      achievement.get: true
      achievement.book: true
      achievement.list: true
      achievement.reload: true
      achievement.give: true
      achievement.check: true
