name: Build project and validate formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.1
    - name: Build project
      run: mvn -B package --file pom.xml
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: advanced-achievements-plugin
        
